[package]
name = "reth-rpc-types-compat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Compatibility layer for reth-primitives and ethereum RPC types"

[lints]
workspace = true

[dependencies]
# ethereum
alloy-rpc-types-eth = { workspace = true, default-features = false, features = ["serde"] }
alloy-consensus.workspace = true

# io
serde.workspace = true
jsonrpsee-types.workspace = true
